name: Deploy Python Lambda for German language web site.

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:    # Allows manual triggering

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Required to checkout repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov
          
      - name: Run tests
        run: |
          pytest --cov=./ --cov-report=xml
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Create deployment package
        run: |
          mkdir -p build
          cp -r *.py build/
          pip install --target ./build -r requirements.txt
          cd build && zip -r ../deployment-package.zip .
          
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://deployment-package.zip
            
      - name: Verify deployment
        run: |
          RESPONSE=$(aws lambda get-function --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --query 'Configuration.LastUpdateStatus' --output text)
          if [[ "$RESPONSE" != "Successful" ]]; then
            echo "Deployment failed or still in progress: $RESPONSE"
            exit 1
          fi
          echo "Lambda function successfully updated"